version: "3.6"

x-build-args: &build_args
<<<<<<< HEAD
  INSTALL_PYTHON_VERSION: "3.7.8"
  INSTALL_NODE_VERSION: "13.14.0"
=======
  INSTALL_PYTHON_VERSION: ""
  INSTALL_NODE_VERSION: ""
>>>>>>> origin/feature

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
<<<<<<< HEAD
    image: "test_app_cc-development"
=======
    image: "testcc-development"
>>>>>>> origin/feature
    ports:
      - "8080:5000"
      - "2992:2992"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
<<<<<<< HEAD
    image: "test_app_cc-production"
=======
    image: "testcc-production"
>>>>>>> origin/feature
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
<<<<<<< HEAD
    image: "test_app_cc-manage"
=======
    image: "testcc-manage"
>>>>>>> origin/feature
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
